#!/bin/bash
# Automated setup script for Synora

set -e

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════╗"
echo "║                                                       ║"
echo "║         SYNORA - ENTERPRISE INTELLIGENCE              ║"
echo "║                 Automated Setup                       ║"
echo "║                                                       ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to prompt for input
prompt_input() {
    local prompt="$1"
    local var_name="$2"
    local default="$3"
    
    if [ -n "$default" ]; then
        read -p "$(echo -e ${YELLOW}${prompt}${NC}) [${default}]: " value
        value="${value:-$default}"
    else
        read -p "$(echo -e ${YELLOW}${prompt}${NC}): " value
    fi
    
    eval "$var_name='$value'"
}

# Function to generate JWT secret
generate_jwt_secret() {
    if command_exists openssl; then
        openssl rand -hex 32
    else
        python3 -c "import secrets; print(secrets.token_hex(32))"
    fi
}

echo -e "${GREEN}✓${NC} Checking prerequisites..."
echo ""

# Check Python
if ! command_exists python3; then
    echo -e "${RED}✗${NC} Python 3 is required but not installed."
    exit 1
fi
echo -e "${GREEN}✓${NC} Python $(python3 --version | awk '{print $2}')"

# Check Node.js
if ! command_exists node; then
    echo -e "${YELLOW}⚠${NC} Node.js not found (required for frontend)"
else
    echo -e "${GREEN}✓${NC} Node.js $(node --version)"
fi

# Check Redis
if ! command_exists redis-cli; then
    echo -e "${YELLOW}⚠${NC} Redis not found. Install with: brew install redis"
    REDIS_NEEDED=true
else
    if redis-cli ping >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} Redis is running"
        REDIS_NEEDED=false
    else
        echo -e "${YELLOW}⚠${NC} Redis installed but not running. Start with: brew services start redis"
        REDIS_NEEDED=true
    fi
fi

echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  API Configuration${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

# Prompt for configuration
echo -e "${GREEN}Google Gemini API (Primary AI Provider)${NC}"
echo "Get your API key from: https://makersuite.google.com/app/apikey"
prompt_input "Google Gemini API Key" GEMINI_API_KEY

echo ""
echo -e "${GREEN}Grok API (Automatic Fallback)${NC}"
echo "Get your API key from: https://console.x.ai"
prompt_input "Grok API Key (optional)" GROK_API_KEY

echo ""
echo -e "${GREEN}Supabase Database${NC}"
echo "Your Supabase URL: https://pbuvixxtexovvemizhws.supabase.co"
prompt_input "Supabase Database Password" SUPABASE_PASSWORD

echo ""
echo -e "${GREEN}Security${NC}"
JWT_SECRET=$(generate_jwt_secret)
echo "Generated JWT Secret: ${JWT_SECRET:0:20}..."

# Create .env files
echo ""
echo -e "${BLUE}Creating configuration files...${NC}"

# Backend .env
cat > apps/api/.env << EOF
# Backend (FastAPI) Environment Variables
# Generated by setup.sh on $(date)

# Supabase Configuration
SUPABASE_URL=https://pbuvixxtexovvemizhws.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidXZpeHh0ZXhvdnZlbWl6aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NDQwNDgsImV4cCI6MjEwMjEyMDA0OH0.xmz2vWW9TBN54NrthRHa-UaqPcLZ5aujNaqEDQxnXEs
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidXZpeHh0ZXhvdnZlbWl6aHdzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjU0NDA0OCwiZXhwIjoyMTAyMTIwMDQ4fQ.twgWKHrxYQGCJma6WcvI0niBAB82zLjS6vGt5Lq3pYo

# Database
DATABASE_URL=postgresql+asyncpg://postgres.pbuvixxtexovvemizhws:${SUPABASE_PASSWORD}@aws-0-us-east-1.pooler.supabase.com:6543/postgres

# DuckDB for Analytics
DUCKDB_PATH=./data/analytics.duckdb

# Redis
REDIS_URL=redis://localhost:6379/0

# JWT Authentication
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=3600
JWT_ALGORITHM=HS256

# AI Providers - Gemini Primary, Grok Fallback
GOOGLE_GEMINI_API_KEY=${GEMINI_API_KEY}
GEMINI_MODEL=gemini-1.5-pro
GROK_API_KEY=${GROK_API_KEY}
GROK_API_URL=https://api.x.ai/v1
AI_FALLBACK_ENABLED=true

# OpenAI (Optional)
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini

# App Configuration
APP_ENV=development
LOG_LEVEL=debug
API_HOST=0.0.0.0
API_PORT=8000

# CORS
CORS_ORIGINS=["http://localhost:3000"]

# File Upload
MAX_UPLOAD_SIZE=104857600
UPLOAD_DIR=./data/uploads
EOF

echo -e "${GREEN}✓${NC} Created apps/api/.env"

# Frontend .env.local
cat > apps/web/.env.local << EOF
# Frontend (Next.js) Environment Variables
# Generated by setup.sh on $(date)

NEXT_PUBLIC_SUPABASE_URL=https://pbuvixxtexovvemizhws.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidXZpeHh0ZXhvdnZlbWl6aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NDQwNDgsImV4cCI6MjEwMjEyMDA0OH0.xmz2vWW9TBN54NrthRHa-UaqPcLZ5aujNaqEDQxnXEs
NEXT_PUBLIC_API_URL=http://localhost:8000
EOF

echo -e "${GREEN}✓${NC} Created apps/web/.env.local"

# Root .env.local (combined)
cat > .env.local << EOF
# Synora Environment Variables
# Generated by setup.sh on $(date)

# ============================================
# Frontend (Next.js) - Public Keys Only
# ============================================
NEXT_PUBLIC_SUPABASE_URL=https://pbuvixxtexovvemizhws.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidXZpeHh0ZXhvdnZlbWl6aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NDQwNDgsImV4cCI6MjEwMjEyMDA0OH0.xmz2vWW9TBN54NrthRHa-UaqPcLZ5aujNaqEDQxnXEs
NEXT_PUBLIC_API_URL=http://localhost:8000

# ============================================
# Backend (FastAPI) - Includes Service Role Key
# ============================================
SUPABASE_URL=https://pbuvixxtexovvemizhws.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidXZpeHh0ZXhvdnZlbWl6aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NDQwNDgsImV4cCI6MjEwMjEyMDA0OH0.xmz2vWW9TBN54NrthRHa-UaqPcLZ5aujNaqEDQxnXEs
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidXZpeHh0ZXhvdnZlbWl6aHdzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjU0NDA0OCwiZXhwIjoyMTAyMTIwMDQ4fQ.twgWKHrxYQGCJma6WcvI0niBAB82zLjS6vGt5Lq3pYo

# Database (Supabase PostgreSQL)
DATABASE_URL=postgresql+asyncpg://postgres.pbuvixxtexovvemizhws:${SUPABASE_PASSWORD}@aws-0-us-east-1.pooler.supabase.com:6543/postgres

# Redis
REDIS_URL=redis://localhost:6379/0

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=3600
JWT_ALGORITHM=HS256

# AI / LLM - Primary: Google Gemini, Fallback: Grok
GOOGLE_GEMINI_API_KEY=${GEMINI_API_KEY}
GEMINI_MODEL=gemini-1.5-pro
GROK_API_KEY=${GROK_API_KEY}
GROK_API_URL=https://api.x.ai/v1
OPENAI_API_KEY=
AI_FALLBACK_ENABLED=true

# App
APP_ENV=development
LOG_LEVEL=debug
API_HOST=0.0.0.0
API_PORT=8000
CORS_ORIGINS=["http://localhost:3000"]
EOF

echo -e "${GREEN}✓${NC} Created .env.local"

# Create data directories
echo ""
echo -e "${BLUE}Creating data directories...${NC}"
mkdir -p apps/api/data/uploads
mkdir -p apps/api/data/analytics
echo -e "${GREEN}✓${NC} Created data directories"

# Install dependencies
echo ""
echo -e "${BLUE}Installing backend dependencies...${NC}"
cd apps/api

# Check if virtual environment exists, if not create it
if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv .venv
fi

# Activate virtual environment
echo "Activating virtual environment..."
source .venv/bin/activate

# Install dependencies in virtual environment
pip install --upgrade pip -q
pip install -r requirements.txt -q

cd ../..
echo -e "${GREEN}✓${NC} Backend dependencies installed"

if command_exists node && [ -d "apps/web" ]; then
    echo ""
    echo -e "${BLUE}Installing frontend dependencies...${NC}"
    cd apps/web
    if command_exists pnpm; then
        pnpm install
    elif command_exists npm; then
        npm install
    fi
    cd ../..
    echo -e "${GREEN}✓${NC} Frontend dependencies installed"
fi

# Validate configuration
echo ""
echo -e "${BLUE}Validating configuration...${NC}"
cd apps/api
python3 scripts/validate_config.py
cd ../..

echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════╗"
echo "║                                                       ║"
echo "║              SETUP COMPLETE! 🎉                       ║"
echo "║                                                       ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Start Redis (if needed):"
echo "   ${BLUE}brew services start redis${NC}"
echo ""
echo "2. Start the backend:"
echo "   ${BLUE}cd apps/api && ./scripts/start.sh${NC}"
echo ""
echo "3. Start the frontend (in another terminal):"
echo "   ${BLUE}cd apps/web && npm run dev${NC}"
echo ""
echo "4. Access the application:"
echo "   Frontend: ${BLUE}http://localhost:3000${NC}"
echo "   API: ${BLUE}http://localhost:8000${NC}"
echo "   API Docs: ${BLUE}http://localhost:8000/docs${NC}"
echo ""
echo "For detailed instructions, see: ${BLUE}CONFIGURATION_GUIDE.md${NC}"
echo ""
